import fs from 'fs';
import { detectOpportunity } from '../../Matrix-Revolution/src/components/robot/engines/opportunities/OpportunityDetector.js';
const raw=fs.readFileSync('C:/Users/Public/Neo-Backtest/data/matrix/COCOA.csv','utf8').split(/\r?\n/).filter(l=>l.trim());
const H=raw[0].split(';').map(h=>h.trim());const toRow=l=>{const v=l.split(';');const o={};H.forEach((h,i)=>{const s=v[i]?.trim();const n=Number(s);o[h]=(s!==''&&Number.isFinite(n))?n:s;});return o;};
const row=toRow(raw.find(l=>l.startsWith('2026.07.07 13:24')));
const r=detectOpportunity(row,'COCOA');
console.log('décision:',r.rawSelection.side,r.rawSelection.strategy,r.rawSelection.profile,'|',r.rawSelection.reasons?.[0]);
console.log('%K s0..s3:',['s0','s1','s2','s3'].map(s=>row['stoch_k_h1_'+s]).join(' '));
console.log('→ min4 =', Math.min(...['s0','s1','s2','s3'].map(s=>Number(row['stoch_k_h1_'+s]))), '· kJump(s0-s1) =', (Number(row['stoch_k_h1_s0'])-Number(row['stoch_k_h1_s1'])).toFixed(2));
console.log('gate catch? min4<20 &&',(Number(row['stoch_k_h1_s0'])-Number(row['stoch_k_h1_s1'])).toFixed(2),'>5 →', (Math.min(...['s0','s1','s2','s3'].map(s=>Number(row['stoch_k_h1_'+s])))<20 && (Number(row['stoch_k_h1_s0'])-Number(row['stoch_k_h1_s1']))>5));
