import fs from "fs"; import path from "path";
const { runMatrixBacktest } = await import("../src/components/simulations/matrixBacktest.mjs");
const D = "C:/Users/Public/Neo-Backtest/data/matrix";
const sig = [];
for (const f of fs.readdirSync(D).filter(x => x.toLowerCase().endsWith(".csv")).sort())
  for (const s of (runMatrixBacktest(path.join(D, f)).signals || [])) if (typeof s.R === "number" && s.obs) sig.push(s);

const PROFILES = ["Sell-off","Strong Bear","Soft Bear","Exhaustion","Soft Bull","Strong Bull","Rally"];
const OBS = ["zone","contact","contactPrev","dominance","instantImpulse","continuationDelta","dailyDirection","dailyForce","thetaRotation","energyState","intensity","stage"];
// grille (niveau -> [par profil])
const K = {
  zone:{EXTREME_BASSE:["TRES_ATTENDU","COMPATIBLE","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],BASSE:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","COMPATIBLE","IMPOSSIBLE","IMPOSSIBLE"],MID:["IMPOSSIBLE","TRES_ATTENDU","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","TRES_ATTENDU","IMPOSSIBLE"],HAUTE:["IMPOSSIBLE","IMPOSSIBLE","COMPATIBLE","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"],EXTREME_HAUTE:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","COMPATIBLE","TRES_ATTENDU"]},
  contact:{CONTACT:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","INDISPENSABLE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],SEPARATED:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"]},
  contactPrev:{CONTACT:["IMPOSSIBLE","IMPOSSIBLE","COMPATIBLE","INDISPENSABLE","COMPATIBLE","IMPOSSIBLE","IMPOSSIBLE"],SEPARATED:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"]},
  dominance:{LOW:["INCOMPATIBLE","INCOMPATIBLE","TRES_ATTENDU","NEUTRE","TRES_ATTENDU","INCOMPATIBLE","INCOMPATIBLE"],MEDIUM:["COMPATIBLE","COMPATIBLE","TRES_ATTENDU","NEUTRE","TRES_ATTENDU","COMPATIBLE","COMPATIBLE"],HIGH:["TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","NEUTRE","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU"],EXTREME:["TRES_ATTENDU","COMPATIBLE","INCOMPATIBLE","NEUTRE","INCOMPATIBLE","COMPATIBLE","TRES_ATTENDU"]},
  instantImpulse:{FAST_UP:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","NEUTRE","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU"],UP:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"],FLAT:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],DOWN:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],FAST_DOWN:["TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","NEUTRE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"]},
  continuationDelta:{POSITIVE:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","NEUTRE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"],NEUTRAL:["COMPATIBLE","COMPATIBLE","COMPATIBLE","NEUTRE","COMPATIBLE","COMPATIBLE","COMPATIBLE"],NEGATIVE:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","NEUTRE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"]},
  dailyDirection:{UP:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","INDISPENSABLE","INDISPENSABLE","INDISPENSABLE"],FLAT:["IMPOSSIBLE","IMPOSSIBLE","COMPATIBLE","IMPOSSIBLE","COMPATIBLE","IMPOSSIBLE","IMPOSSIBLE"],DOWN:["INDISPENSABLE","INDISPENSABLE","INDISPENSABLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"]},
  dailyForce:{LOW:["IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE"],MEDIUM:["IMPOSSIBLE","IMPOSSIBLE","INDISPENSABLE","COMPATIBLE","INDISPENSABLE","IMPOSSIBLE","IMPOSSIBLE"],HIGH:["TRES_ATTENDU","INDISPENSABLE","COMPATIBLE","TRES_ATTENDU","COMPATIBLE","INDISPENSABLE","TRES_ATTENDU"],EXTREME:["INDISPENSABLE","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","INDISPENSABLE"]},
  thetaRotation:{ROT_UP_FAST:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU"],ROT_UP:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"],STABLE:["IMPOSSIBLE","COMPATIBLE","COMPATIBLE","IMPOSSIBLE","COMPATIBLE","COMPATIBLE","IMPOSSIBLE"],ROT_DOWN:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],ROT_DOWN_FAST:["TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"]},
  energyState:{ACCELERATING:["TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","IMPOSSIBLE","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU"],STABLE:["COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE"],DECELERATING:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],DEAD:["NEUTRE","NEUTRE","NEUTRE","NEUTRE","NEUTRE","NEUTRE","NEUTRE"]},
  intensity:{LOW:["IMPOSSIBLE","IMPOSSIBLE","COMPATIBLE","NEUTRE","COMPATIBLE","IMPOSSIBLE","IMPOSSIBLE"],MEDIUM:["IMPOSSIBLE","COMPATIBLE","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","COMPATIBLE","IMPOSSIBLE"],HIGH:["TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU","COMPATIBLE","TRES_ATTENDU","TRES_ATTENDU","TRES_ATTENDU"],EXTREME:["TRES_ATTENDU","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","TRES_ATTENDU"]},
  stage:{EARLY:["IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE"],MID:["IMPOSSIBLE","TRES_ATTENDU","TRES_ATTENDU","IMPOSSIBLE","TRES_ATTENDU","TRES_ATTENDU","IMPOSSIBLE"],LATE_BUY:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","TRES_ATTENDU","COMPATIBLE","COMPATIBLE","COMPATIBLE"],LATE_SELL:["COMPATIBLE","COMPATIBLE","COMPATIBLE","TRES_ATTENDU","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],EXHAUSTED_BUY:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","INDISPENSABLE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"],EXHAUSTED_SELL:["IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE","INDISPENSABLE","IMPOSSIBLE","IMPOSSIBLE","IMPOSSIBLE"]},
};
const pIdx = Object.fromEntries(PROFILES.map((p, i) => [p, i]));
// régimes qui tirent réellement (CONT) : Soft/Strong Bull/Bear
const REG = ["Soft Bull","Strong Bull","Soft Bear","Strong Bear"];
console.log("CONTRADICTIONS grille ↔ présence réelle (signaux CONT fired) :\n");
for (const prof of REG) {
  const rows = sig.filter(s => s.profile === prof);
  const idx = pIdx[prof];
  const flags = [];
  for (const obs of OBS) {
    const vals = rows.map(s => s.obs[obs]).filter(v => v != null);
    const N = vals.length; if (!N) continue;
    const counts = {}; for (const v of vals) counts[v] = (counts[v] || 0) + 1;
    for (const [lvl, c] of Object.entries(counts)) {
      const label = K[obs]?.[lvl]?.[idx]; if (!label) continue;
      const pct = (c / N * 100);
      if (label === "IMPOSSIBLE" && pct >= 3) flags.push(`  ⛔→présent  ${obs}=${lvl.padEnd(13)} ${pct.toFixed(0).padStart(3)}% mais IMPOSSIBLE`);
    }
    // INDISPENSABLE absent ?
    for (const [lvl, arr] of Object.entries(K[obs] || {})) {
      if (arr[idx] === "INDISPENSABLE") { const pct = (counts[lvl] || 0) / N * 100; if (pct < 90) flags.push(`  ⚠ requis-absent ${obs}=${lvl.padEnd(13)} ${pct.toFixed(0).padStart(3)}% mais INDISPENSABLE`); }
    }
  }
  console.log(`### ${prof}  (n=${rows.length})`);
  console.log(flags.length ? flags.join("\n") : "  (cohérent)");
  console.log("");
}
