import path from "path";
const { runMatrixBacktest } = await import("../src/components/simulations/matrixBacktest.mjs");
const D = "C:/Users/Public/Neo-Backtest/data/matrix";
const run=(asset,opts)=>{const sigs=(runMatrixBacktest(path.join(D,asset+".csv"),opts).signals||[]).filter(s=>typeof s.R==="number");
  const w=sigs.filter(s=>s.outcome==="WIN").length,l=sigs.filter(s=>s.outcome==="LOSS").length,R=sigs.reduce((x,s)=>x+s.R,0);
  return {n:sigs.length,wr:(w+l)?w/(w+l)*100:0,R,avg:sigs.length?R/sigs.length:0,tp:sigs[0]?.tp!=null};};
const show=(label,r)=>console.log(`  ${label.padEnd(28)} n ${String(r.n).padStart(4)} · WR ${r.wr.toFixed(1)}% · avgR ${(r.avg>=0?"+":"")+r.avg.toFixed(3)} · R ${(r.R>=0?"+":"")+r.R.toFixed(1)}`);
console.log("=== US500 (WIP) — TP/SL ===");
show("défaut (config par actif)", run("US_500",{}));
show("tp=0,55 sl=1,85 (owner)", run("US_500",{tpAtr:0.55,slAtr:1.85}));
show("tp=0,65 sl=1,95", run("US_500",{tpAtr:0.65,slAtr:1.95}));
console.log("\n=== COCOA (WIP) — TP/SL ===");
show("défaut", run("COCOA",{}));
show("tp=0,65 sl=1,95 (~1:3)", run("COCOA",{tpAtr:0.65,slAtr:1.95}));
show("tp=1,0 sl=3,0 (1:3 large)", run("COCOA",{tpAtr:1.0,slAtr:3.0}));
console.log("\n=== GOLD (WIP) — le laggard, plus large ? ===");
show("défaut", run("GOLD",{}));
show("tp=1,0 sl=3,0", run("GOLD",{tpAtr:1.0,slAtr:3.0}));
show("tp=1,3 sl=3,9", run("GOLD",{tpAtr:1.3,slAtr:3.9}));
