import fs from 'fs';
import { detectOpportunity, maturityGate } from '../../Matrix-Revolution/src/components/robot/engines/opportunities/OpportunityDetector.js';
import { observeProfile } from '../../Matrix-Revolution/src/components/robot/engines/opportunities/classifyMarketProfile.js';
const raw = fs.readFileSync('C:/Users/Public/Neo-Backtest/data/matrix/COCOA.csv','utf8').split(/\r?\n/).filter(l=>l.trim());
const H = raw[0].split(';').map(h=>h.trim());
const toRow = l => { const v=l.split(';'); const o={}; H.forEach((h,i)=>{const s=v[i]?.trim();const n=Number(s);o[h]=(s!==''&&Number.isFinite(n))?n:s;}); return o; };
const line = raw.find(l=>l.startsWith('2026.07.07 13:24')); if(!line){console.log('introuvable');process.exit(0);}
const row = toRow(line); const r = detectOpportunity(row,'COCOA'); const m = maturityGate(row);
const obs = observeProfile({vector:r.vector,energy:r.energy,maturity:m,stoch:r.stoch});
const h1 = r.stoch.perTf.h1, p = m.perTf.h1;
console.log(`COCOA ${row.timestamp}`);
console.log(`DÉCISION : ${r.rawSelection.side}/${r.rawSelection.strategy} ${r.rawSelection.profile} conf=${r.rawSelection.confidence} gap=${r.rawSelection.gap}`);
console.log(`  reason : ${r.rawSelection.reasons?.[0]}`);
console.log(`\nRANKING c2 : ${r.marketProfile.ranking.map(([n,c])=>`${n} ${c.toFixed(3)}`).join(' · ')}`);
console.log(`\nOBSERVABLES :`);
for (const k of ['stage','zone','contact','instantImpulse','dailyDirection','dailyForce','energyState','intensity','dominance','thetaRotation','continuationDelta']) console.log(`  ${k.padEnd(18)} ${obs[k]}`);
console.log(`\nSTAGE décompo : state=${m.state} score=${m.score} z=${m.zscoreH1} (${m.zscoreH1>=0?'BUY':'SELL'})  contribs h1: rsi=${p.rsi} wr=${p.wr} zscore=${p.zscore} stoch=${p.stoch} tdr=${p.tdr}`);
console.log(`STOCH h1 : %K=${h1.k} %D=${h1.d} zone=${h1.zone} contact=${h1.contact} cross=${h1.kd?.crossoverState}/${h1.kd?.crossAge}`);
console.log(`bruts h1 : RSI=${row['rsi_h1_s0']} zscore=${row['zscore_h1_s0']} %K=${row['stoch_k_h1_s0']} ADX=${row['adx14_h1_s0']} intradayChg=${row['intraday_change']}`);
console.log(`VECTOR : dailyDir=${r.vector.dailyDirection} force=${r.vector.forceScore} thetaDay=${r.vector.thetaDay} vScore=${r.vector.score}`);
